id: ICF3C12CD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T02:37:48+00:00'
last_modified: '2022-06-08T17:59:26.266962+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29234
  title: མདོ་རྒྱུད་བསྟན་བཅོས་ཀུན་ལས་བཏུས་པའི་ཆོས་ཀྱི་རྣམ་གྲངས་མུ་ཐི་ལའི་འཕྲེང་བ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F075:
      image_group_id: I5255
      title: ''
      total_pages: 320
      order: 1
      base_file: F075.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
