id: P008038
initial_creation_type: ocr
source_metadata:
  id: bdr:W29234
  title: མདོ་རྒྱུད་བསྟན་བཅོས་ཀུན་ལས་བཏུས་པའི་ཆོས་ཀྱི་རྣམ་གྲངས་མུ་ཐི་ལའི་འཕྲེང་བ
  author: ''
  volumes:
    d188142fa2bc4d82ab5c5e38308c63ff:
      image_group_id: I5255
      title: ''
      volume_number: 1
      total_pages: 320
      base_file: v001.txt
ebook_metadata:
  title: མདོ་རྒྱུད་བསྟན་བཅོས་ཀུན་ལས་བཏུས་པའི་ཆོས་ཀྱི་རྣམ་གྲངས་མུ་ཐི་ལའི་འཕྲེང་བ
  author: ''
  sku: P008038
  cover: cover.jpg
  layers:
  - pagination
